{"name": "Test of failed attempt to login with the wrong fields", "status": "failed", "statusDetails": {"message": "AssertionError: Error message contains wrong text\nassert '{\"code\":404,... не найдена\"}' == '\"message\": \"...ь не найдена\"'\n  - \"message\": \"Учетная запись не найдена\"\n  ?           -\n  + {\"code\":404,\"message\":\"Учетная запись не найдена\"}\n  ? ++++++++++++                                     +", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x000001E7A01E5AD0>, new_courier = (<Response [201]>, ['oatyuwcomg', 'utchphynbi', 'olbdyysxwf']), wrong_field = 'login'\n\n    @allure.title('Test of failed attempt to login with the wrong fields')\n    @allure.description('Negative test of the endpoint \"Логин курьера в системе\" POST /api/v1/courier/login.'\n                        'Parameterized test, checks impossibility of authorization '\n                        'when any of the mandatory fields is wrong')\n    @pytest.mark.parametrize(\"wrong_field\", [\"login\", \"password\"])\n    def test_login_with_any_wrong_field_failed(self, new_courier, wrong_field):\n        login_pass = new_courier[1]\n        payload = {\n            \"login\": login_pass[0],\n            \"password\": login_pass[1]\n        }\n        payload[wrong_field] = f'{payload[wrong_field]}a'\n        response = requests.post(f'{url}/api/v1/courier/login', data=payload)\n        assert response.status_code == 404, f'Instead of an error code 404 received code {response.status_code}'\n>       assert response.text == '\"message\": \"Учетная запись не найдена\"', f'Error message contains wrong text'\nE       AssertionError: Error message contains wrong text\nE       assert '{\"code\":404,... не найдена\"}' == '\"message\": \"...ь не найдена\"'\nE         - \"message\": \"Учетная запись не найдена\"\nE         ?           -\nE         + {\"code\":404,\"message\":\"Учетная запись не найдена\"}\nE         ? ++++++++++++                                     +\n\ntests\\test_courier_login.py:54: AssertionError"}, "description": "Negative test of the endpoint \"Логин курьера в системе\" POST /api/v1/courier/login.Parameterized test, checks impossibility of authorization when any of the mandatory fields is wrong", "parameters": [{"name": "wrong_field", "value": "'login'"}], "start": 1698928091610, "stop": 1698928092031, "uuid": "e7d0f7f7-8994-4e11-a7d8-366fa00ba383", "historyId": "232207e8de485095a45435a34197cc90", "testCaseId": "67167e8a3582672514a127bcef0528c3", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_with_any_wrong_field_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Airforce3"}, {"name": "thread", "value": "13800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}