{"name": "Test of failed attempt to login with the missing field", "status": "failed", "statusDetails": {"message": "AssertionError: Error message contains wrong text\nassert '{\"code\":400,...х для входа\"}' == '\"message\":  ...ых для входа\"'\n  - \"message\":  \"Недостаточно данных для входа\"\n  ?           --\n  + {\"code\":400,\"message\":\"Недостаточно данных для входа\"}\n  ? ++++++++++++                                         +", "trace": "self = <tests.test_courier_login.TestCourierLogin object at 0x0000022DD3364BD0>, new_courier = (<Response [201]>, ['cvuawveime', 'xqdpxgqtth', 'hdyuvybfto']), login_missing = True\n\n    @allure.title('Test of failed attempt to login with the missing field')\n    @allure.description('Negative test of the endpoint \"Логин курьера в системе\" POST /api/v1/courier/login.'\n                        'Parameterized test, checks impossibility of authorization '\n                        'when any of the mandatory fields is missing')\n    @pytest.mark.parametrize(\"login_missing\", [True, False])\n    def test_login_with_any_missing_field_failed(self, new_courier, login_missing):\n        login_pass = new_courier[1]\n        payload = {}\n        if not login_missing:\n            payload[\"login\"] = login_pass[0]\n        else:\n            payload[\"password\"] = login_pass[1]\n        response = requests.post(f'{url}/api/v1/courier/login', data=payload)\n        assert response.status_code == 400, f'Instead of an error code 400 received code {response.status_code}'\n>       assert response.text == '\"message\":  \"Недостаточно данных для входа\"', f'Error message contains wrong text'\nE       AssertionError: Error message contains wrong text\nE       assert '{\"code\":400,...х для входа\"}' == '\"message\":  ...ых для входа\"'\nE         - \"message\":  \"Недостаточно данных для входа\"\nE         ?           --\nE         + {\"code\":400,\"message\":\"Недостаточно данных для входа\"}\nE         ? ++++++++++++                                         +\n\ntests\\test_courier_login.py:38: AssertionError"}, "description": "Negative test of the endpoint \"Логин курьера в системе\" POST /api/v1/courier/login.Parameterized test, checks impossibility of authorization when any of the mandatory fields is missing", "attachments": [{"name": "stdout", "source": "396846b2-aa1c-48ce-98fa-557ec929524d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "login_missing", "value": "True"}], "start": 1698833291269, "stop": 1698833291708, "uuid": "63bb1a23-668e-4ed2-b59d-59141e774030", "historyId": "31aafe5995a09eba47a781734ce212af", "testCaseId": "45afb257416271363439351dc062b346", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_with_any_missing_field_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "Airforce3"}, {"name": "thread", "value": "12480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}